package uz.hrlab.grading.integration.imports.application;

import org.springframework.stereotype.Component;
import uz.hrlab.grading.integration.excel.ExcelWriter;
import uz.hrlab.grading.integration.excel.GuideSheet;
import uz.hrlab.grading.integration.imports.domain.ImportTemplateCode;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates empty + sample XLSX bytes for the 5 supported import templates.
 * Backs {@code GET /api/v1/imports/templates/{code}/empty.xlsx} and
 * {@code GET /api/v1/imports/templates/{code}/sample.xlsx} — see
 * {@code po-import-template-samples-spec.md}.
 *
 * <p>All cells go through {@link ExcelWriter} (which routes user-originated
 * strings through {@code SafeCellWriter}). Sample data is realistic ACME
 * Holdings content matching the seeded demo project.
 */
@Component
public class ImportTemplateSamples {

    /** Banner cell written into row 1 column A of every generated template. */
    public static final String DEMO_HEADER =
            "Generated by grading.hrlab.uz (DEMO) - ACME Holdings";

    private final ExcelWriter excelWriter = new ExcelWriter();
    private final ImportTemplateRegistry registry;
    private final ImportTemplateGuide guide;

    public ImportTemplateSamples(ImportTemplateRegistry registry, ImportTemplateGuide guide) {
        this.registry = registry;
        this.guide = guide;
    }

    public List<String> headersFor(String templateCode) {
        ImportTemplateDefinition def = registry.find(templateCode)
                .orElseThrow(() -> new IllegalArgumentException(
                        "Unknown template: " + templateCode));
        List<String> headers = new ArrayList<>(def.requiredColumns());
        for (String opt : def.optionalColumns()) {
            if (!headers.contains(opt)) headers.add(opt);
        }
        // Extended optional columns per PO spec §4 (not yet known by registry).
        addExtraHeaders(templateCode, headers);
        return headers;
    }

    /** Empty template = header row only (one trivial demo row with the banner). */
    public byte[] generateEmpty(String templateCode) {
        List<String> headers = headersFor(templateCode);
        // One "instructions" row carrying the DEMO banner in the first column.
        Map<String, String> banner = new HashMap<>();
        banner.put(headers.get(0), DEMO_HEADER);
        String dataSheet = sheetName(templateCode);
        GuideSheet guideSheet = guide.buildFor(templateCode, dataSheet);
        return excelWriter.write(dataSheet, headers, List.of(banner), guideSheet);
    }

    /** Sample template = headers + ACME sample rows per §5 of the PO spec. */
    public byte[] generateSample(String templateCode) {
        List<String> headers = headersFor(templateCode);
        List<Map<String, String>> rows = new ArrayList<>();
        // Banner row first.
        Map<String, String> banner = new HashMap<>();
        banner.put(headers.get(0), DEMO_HEADER);
        rows.add(banner);

        switch (templateCode) {
            case ImportTemplateCode.ORG_STRUCTURE_V1     -> rows.addAll(orgStructureSample());
            case ImportTemplateCode.POSITION_CATALOG_V1  -> rows.addAll(positionCatalogSample());
            case ImportTemplateCode.JOB_PROFILE_V1       -> rows.addAll(jobProfileSample());
            case ImportTemplateCode.METHODOLOGY_FACTORS_V1 -> rows.addAll(methodologyFactorsSample());
            case ImportTemplateCode.GRADE_BANDS_V1       -> rows.addAll(gradeBandsSample());
            default -> throw new IllegalArgumentException("Unknown template: " + templateCode);
        }
        String dataSheet = sheetName(templateCode);
        GuideSheet guideSheet = guide.buildFor(templateCode, dataSheet);
        return excelWriter.write(dataSheet, headers, rows, guideSheet);
    }

    /** Suggested filename (no extension) for HTTP Content-Disposition. */
    public String filename(String templateCode, boolean sample) {
        return templateCode + (sample ? "_sample" : "_empty") + ".xlsx";
    }

    // -----------------------------------------------------------------
    // Sample row builders (ACME Holdings)
    // -----------------------------------------------------------------

    private List<Map<String, String>> orgStructureSample() {
        List<Map<String, String>> out = new ArrayList<>();
        out.add(orgRow("CEO-OFFICE",     "CEO Office",              "",            1, "DIVISION",   "HQ", "CC-001", "Holding executive office"));
        out.add(orgRow("CFO-OFFICE",     "CFO Office",              "CEO-OFFICE",  2, "DIVISION",   "HQ", "CC-100", "Finance"));
        out.add(orgRow("CTO-OFFICE",     "CTO Office",              "CEO-OFFICE",  2, "DIVISION",   "HQ", "CC-200", "Technology"));
        out.add(orgRow("HR-OFFICE",      "HR Office",               "CEO-OFFICE",  2, "DIVISION",   "HQ", "CC-300", "People"));
        out.add(orgRow("OPS-OFFICE",     "Operations Office",       "CEO-OFFICE",  2, "DIVISION",   "HQ", "CC-400", "Operations"));
        out.add(orgRow("FIN-DEPT",       "Finance Department",      "CFO-OFFICE",  3, "DEPARTMENT", "HQ", "CC-110", "FP&A"));
        out.add(orgRow("TREASURY-DEPT",  "Treasury Department",     "CFO-OFFICE",  3, "DEPARTMENT", "HQ", "CC-120", "Cash & banking"));
        out.add(orgRow("IT-INFRA-DEPT",  "IT Infrastructure",       "CTO-OFFICE",  3, "DEPARTMENT", "HQ", "CC-210", "Infra"));
        out.add(orgRow("SW-ENG-DEPT",    "Software Engineering",    "CTO-OFFICE",  3, "DEPARTMENT", "HQ", "CC-220", "Engineering"));
        out.add(orgRow("HR-OPS-DEPT",    "HR Operations",           "HR-OFFICE",   3, "DEPARTMENT", "HQ", "CC-310", "Payroll & admin"));
        out.add(orgRow("TALENT-DEPT",    "Talent Acquisition",      "HR-OFFICE",   3, "DEPARTMENT", "HQ", "CC-320", "Recruiting"));
        out.add(orgRow("OPS-DEPT",       "Operations",              "OPS-OFFICE",  3, "DEPARTMENT", "HQ", "CC-410", "Ops"));
        return out;
    }

    private Map<String, String> orgRow(String code, String name, String parent,
                                       int level, String type, String location,
                                       String costCenter, String desc) {
        Map<String, String> r = new LinkedHashMap<>();
        r.put("external_id", code);
        r.put("name", name);
        r.put("parent_external_id", parent);
        r.put("level", String.valueOf(level));
        r.put("type", type);
        r.put("location_code", location);
        r.put("cost_center_code", costCenter);
        r.put("description", desc);
        return r;
    }

    private List<Map<String, String>> positionCatalogSample() {
        List<Map<String, String>> out = new ArrayList<>();
        out.add(positionRow("POS-CFO",        "CFO",                       "CFO-OFFICE",     "ACTIVE", "MANAGEMENT", "MANAGER",   "Finance",     "C-level", 1, ""));
        out.add(positionRow("POS-SR-FIN",     "Senior Financial Analyst",  "FIN-DEPT",       "ACTIVE", "SPECIALIST", "SPECIALIST","Finance",     "Senior",  2, ""));
        out.add(positionRow("POS-FIN",        "Financial Analyst",         "FIN-DEPT",       "ACTIVE", "SPECIALIST", "SPECIALIST","Finance",     "Mid",     3, ""));
        out.add(positionRow("POS-HEAD-TR",    "Head of Treasury",          "TREASURY-DEPT",  "ACTIVE", "MANAGEMENT", "MANAGER",   "Treasury",    "Lead",    1, ""));
        out.add(positionRow("POS-TR",         "Treasury Specialist",       "TREASURY-DEPT",  "ACTIVE", "SPECIALIST", "SPECIALIST","Treasury",    "Mid",     2, ""));
        out.add(positionRow("POS-CTO",        "CTO",                       "CTO-OFFICE",     "ACTIVE", "MANAGEMENT", "MANAGER",   "Engineering", "C-level", 1, ""));
        out.add(positionRow("POS-VP-ENG",     "VP Engineering",            "CTO-OFFICE",     "ACTIVE", "MANAGEMENT", "MANAGER",   "Engineering", "VP",      1, ""));
        out.add(positionRow("POS-SR-SWE",     "Senior Software Engineer",  "SW-ENG-DEPT",    "ACTIVE", "SPECIALIST", "SPECIALIST","Engineering", "Senior",  4, ""));
        out.add(positionRow("POS-SWE",        "Software Engineer",         "SW-ENG-DEPT",    "ACTIVE", "SPECIALIST", "SPECIALIST","Engineering", "Mid",     6, ""));
        out.add(positionRow("POS-JR-SWE",     "Junior Engineer",           "SW-ENG-DEPT",    "ACTIVE", "SPECIALIST", "SPECIALIST","Engineering", "Junior",  3, ""));
        out.add(positionRow("POS-HRD",        "HR Director",               "HR-OFFICE",      "ACTIVE", "MANAGEMENT", "MANAGER",   "HR",          "Director",1, ""));
        out.add(positionRow("POS-HRBP",       "HR Business Partner",       "HR-OPS-DEPT",    "ACTIVE", "SPECIALIST", "SPECIALIST","HR",          "Senior",  2, ""));
        out.add(positionRow("POS-REC",        "Recruiter",                 "TALENT-DEPT",    "ACTIVE", "SPECIALIST", "SPECIALIST","HR",          "Mid",     3, ""));
        out.add(positionRow("POS-OPS-MGR",    "Operations Manager",        "OPS-DEPT",       "ACTIVE", "MANAGEMENT", "MANAGER",   "Operations",  "Manager", 1, ""));
        out.add(positionRow("POS-OPS",        "Operations Specialist",     "OPS-DEPT",       "ACTIVE", "OPERATIONAL","SPECIALIST","Operations",  "Mid",     5, ""));
        return out;
    }

    private Map<String, String> positionRow(String code, String title, String dept,
                                            String status, String fn, String category,
                                            String family, String level, int headcount,
                                            String gradeCode) {
        Map<String, String> r = new LinkedHashMap<>();
        r.put("external_id", code);
        r.put("title", title);
        r.put("department_external_id", dept);
        r.put("status", status);
        r.put("function", fn);
        r.put("category", category);
        r.put("job_family", family);
        r.put("job_level", level);
        r.put("headcount", String.valueOf(headcount));
        r.put("grade_code", gradeCode);
        return r;
    }

    /**
     * Job-profile sample. IMPORT ORDER MATTERS: every {@code position_external_id}
     * below (POS-CFO, POS-CTO, POS-SR-SWE, POS-HRD, POS-OPS-MGR) is one of the
     * codes created by {@link #positionCatalogSample()} — so this sample is only
     * importable AFTER the org-structure and position-catalog templates have
     * been imported into the same project. {@code JobProfileRowCommitter} fails
     * a row with MISSING_POSITION when the referenced position does not yet
     * exist. The full import order is: org structure → positions → job profiles.
     * Each row creates a single DRAFT profile; re-importing the same position
     * yields PROFILE_ALREADY_EXISTS (one active profile per position).
     */
    private List<Map<String, String>> jobProfileSample() {
        List<Map<String, String>> out = new ArrayList<>();
        out.add(profileRow("POS-CFO",
                "Lead the holding's financial strategy, treasury and FP&A.",
                "Own budgeting; lead audits; report to Board; manage CFO Office.",
                "Group financial health; reporting accuracy; capital allocation.",
                "Approve budgets up to USD 5M; sign banking facilities.",
                "EBITDA growth; on-time monthly close; audit findings = 0 high.",
                "MBA or Master Finance; CFA preferred.",
                "10+ years finance leadership; 3+ years CFO/VP Finance.",
                "Corporate finance; M&A; IFRS; SAP S/4; risk management.",
                "HQ office; ~40h/wk; occasional international travel.",
                "2026-01-15"));
        out.add(profileRow("POS-CTO",
                "Define and execute the technology strategy of ACME Holdings.",
                "Lead engineering, infrastructure, data, security and architecture.",
                "Platform reliability and engineering productivity.",
                "Approve technical roadmaps and architecture decisions.",
                "Uptime >= 99.9%; deployment frequency; security incidents = 0 critical.",
                "MSc Computer Science or equivalent.",
                "10+ years in tech leadership.",
                "Cloud architecture; security; org design; agile.",
                "HQ office; on-call rotation as needed.",
                "2026-01-15"));
        out.add(profileRow("POS-SR-SWE",
                "Build and maintain mission-critical platform services.",
                "Design services; review code; mentor engineers; ship features.",
                "Service quality and team mentorship.",
                "Approve PRs in own service area; design RFCs.",
                "P95 latency targets; bug SLAs; mentee growth.",
                "BSc Computer Science or 5+ years experience.",
                "5+ years backend engineering.",
                "Java/Kotlin; PostgreSQL; AWS; distributed systems.",
                "Hybrid; 40h/wk; occasional on-call.",
                "2026-01-15"));
        out.add(profileRow("POS-HRD",
                "Lead HR strategy across the holding.",
                "Own talent, performance, comp; partner with executives.",
                "People function and culture health.",
                "Approve org changes up to band L9; comp adjustments.",
                "Voluntary turnover; engagement score; time-to-fill.",
                "BSc or MSc HR Management.",
                "8+ years HR including 3 years senior leadership.",
                "Comp & ben; talent acquisition; OD; labor law.",
                "HQ office; 40h/wk.",
                "2026-01-15"));
        out.add(profileRow("POS-OPS-MGR",
                "Run operations of the Operations Office.",
                "Plan capacity; monitor KPIs; coordinate cross-team.",
                "Operational throughput and quality.",
                "Approve schedules and operational changes.",
                "Throughput; defect rate; cost per unit.",
                "BSc Industrial Engineering or Business.",
                "7+ years operations management.",
                "Lean; Six Sigma; ERP systems.",
                "On-site; 40h/wk; occasional shift work.",
                "2026-01-15"));
        return out;
    }

    private Map<String, String> profileRow(String posCode, String purpose,
                                           String duties, String area,
                                           String authority, String kpi,
                                           String education, String experience,
                                           String knowledge, String working,
                                           String actualization) {
        Map<String, String> r = new LinkedHashMap<>();
        r.put("position_external_id", posCode);
        r.put("purpose", purpose);
        r.put("main_duties", duties);
        r.put("responsibility_area", area);
        r.put("authority", authority);
        r.put("kpi_expected_results", kpi);
        r.put("education_requirements", education);
        r.put("experience_requirements", experience);
        r.put("knowledge_skills", knowledge);
        r.put("working_conditions", working);
        r.put("actualization_date", actualization);
        return r;
    }

    /**
     * Methodology sample — ONE approvable CLASSIC_8_FACTOR methodology. The
     * methodology-level metadata columns are repeated identically on every row
     * (one methodology per file, per {@code MethodologyFactorsRowCommitter});
     * 8 factors × 5 levels = 40 factor/level rows. Weights are 12.5 each so the
     * sum is 100 — valid for {@code WEIGHTED_POINTS} — and every factor has ≥2
     * levels, so the imported DRAFT passes {@code ApproveMethodologyVersionUseCase}.
     */
    private List<Map<String, String>> methodologyFactorsSample() {
        // Methodology-level metadata — identical on every row (one per file).
        String methodologyCode = "ACME-GRADING";
        String methodologyName = "Методология грейдирования ACME";
        String methodologyType = "CLASSIC_8_FACTOR";
        String scoringMode = "WEIGHTED_POINTS";
        String targetTotalPoints = "1000";

        String methodologyNameUz = "ACME грейдлаш методологияси";

        String[] factors = {
                "KNOWLEDGE",        "Knowledge",
                "EXPERIENCE",       "Experience",
                "COMPLEXITY",       "Complexity",
                "RESPONSIBILITY",   "Responsibility",
                "AUTONOMY",         "Autonomy",
                "INFLUENCE",        "Influence",
                "COMMUNICATION",    "Communication",
                "WORKING_CONDITIONS","Working conditions",
        };
        // Uzbek (Cyrillic) siblings of the factor names above, same order — they
        // demonstrate the optional `_uz` columns so a downloaded template shows
        // HR exactly where the second language goes.
        String[] factorsUz = {
                "Билим", "Тажриба", "Мураккаблик", "Масъулият",
                "Мустақиллик", "Таъсир", "Коммуникация", "Меҳнат шароити",
        };
        String[] levels = { "L1 Basic", "L2 Beginning", "L3 Intermediate", "L4 Advanced", "L5 Expert" };
        String[] levelsUz = {
                "1-даража (бошланғич)", "2-даража (базавий)", "3-даража (ўрта)",
                "4-даража (юқори)", "5-даража (эксперт)",
        };
        int[]    points = { 40, 80, 120, 160, 200 };
        String   weight = "12.5"; // 8 × 12.5 = 100 → valid WEIGHTED_POINTS sum

        List<Map<String, String>> out = new ArrayList<>();
        for (int f = 0; f < factors.length; f += 2) {
            String code = factors[f];
            String name = factors[f + 1];
            for (int l = 0; l < levels.length; l++) {
                Map<String, String> r = new LinkedHashMap<>();
                // Methodology-level metadata (same on every row).
                r.put("methodology_code", methodologyCode);
                r.put("methodology_name", methodologyName);
                r.put("methodology_name_uz", methodologyNameUz);
                r.put("methodology_type", methodologyType);
                r.put("scoring_mode", scoringMode);
                r.put("target_total_points", targetTotalPoints);
                // Per-factor/level columns.
                r.put("factor_code", code);
                r.put("factor_name", name);
                r.put("factor_name_uz", factorsUz[f / 2]);
                // Registry-required columns for METHODOLOGY_FACTORS_V1.
                r.put("weight", weight);
                r.put("score", String.valueOf(points[l]));
                r.put("level_code", "L" + (l + 1));
                r.put("level_name", levels[l]);
                r.put("level_name_uz", levelsUz[l]);
                // Duplicate informational columns (kept in sync with weight/score).
                r.put("factor_weight", weight);
                r.put("level_points", String.valueOf(points[l]));
                r.put("level_order", String.valueOf(l + 1));
                r.put("level_description", name + " - " + levels[l]);
                r.put("level_description_uz", factorsUz[f / 2] + " — " + levelsUz[l]);
                out.add(r);
            }
        }
        return out;
    }

    private List<Map<String, String>> gradeBandsSample() {
        String[] labels = {
                "Junior", "Junior+", "Specialist", "Specialist+",
                "Senior Specialist", "Lead Specialist", "Team Lead",
                "Senior Lead", "Manager", "Senior Manager",
                "Department Head", "Director", "VP", "C-level",
        };
        List<Map<String, String>> out = new ArrayList<>();
        for (int i = 0; i < 14; i++) {
            String min = i == 0 ? "0" : (i * 50) + ".0001";
            String max = ((i + 1) * 50) + "";
            Map<String, String> r = new LinkedHashMap<>();
            // grade_code is parsed as a positive integer grade_number by
            // GradeBandsRowCommitter — plain digits, not a letter-prefixed code.
            r.put("grade_code", String.valueOf(i + 1));
            r.put("min_score", min);
            r.put("max_score", max);
            r.put("label", labels[i]);
            r.put("description", "Grade " + (i + 1) + " - " + labels[i]);
            out.add(r);
        }
        return out;
    }

    private static String sheetName(String templateCode) {
        // Keep <= 31 chars per Excel limit.
        return switch (templateCode) {
            case ImportTemplateCode.ORG_STRUCTURE_V1        -> "Departments";
            case ImportTemplateCode.POSITION_CATALOG_V1     -> "Positions";
            case ImportTemplateCode.JOB_PROFILE_V1          -> "Profiles";
            case ImportTemplateCode.METHODOLOGY_FACTORS_V1  -> "Factors";
            case ImportTemplateCode.GRADE_BANDS_V1          -> "Grades";
            default -> "Sheet1";
        };
    }

    /**
     * Registry knows the core required/optional columns; this method extends
     * with the PO-spec columns (description / cost_center / headcount / etc.)
     * that don't exist on the live parser yet but ship in the template UI.
     */
    private static void addExtraHeaders(String templateCode, List<String> headers) {
        switch (templateCode) {
            case ImportTemplateCode.ORG_STRUCTURE_V1 -> {
                if (!headers.contains("type")) headers.add("type");
                if (!headers.contains("cost_center_code")) headers.add("cost_center_code");
                if (!headers.contains("description")) headers.add("description");
            }
            case ImportTemplateCode.POSITION_CATALOG_V1 -> {
                if (!headers.contains("function")) headers.add("function");
                if (!headers.contains("category")) headers.add("category");
                if (!headers.contains("job_family")) headers.add("job_family");
                if (!headers.contains("job_level")) headers.add("job_level");
                if (!headers.contains("headcount")) headers.add("headcount");
            }
            case ImportTemplateCode.JOB_PROFILE_V1 -> {
                if (!headers.contains("authority")) headers.add("authority");
                if (!headers.contains("kpi_expected_results")) headers.add("kpi_expected_results");
                if (!headers.contains("education_requirements")) headers.add("education_requirements");
                if (!headers.contains("experience_requirements")) headers.add("experience_requirements");
                if (!headers.contains("knowledge_skills")) headers.add("knowledge_skills");
                if (!headers.contains("working_conditions")) headers.add("working_conditions");
                if (!headers.contains("actualization_date")) headers.add("actualization_date");
            }
            case ImportTemplateCode.METHODOLOGY_FACTORS_V1 -> {
                // registry calls them factor_weight as 'weight' / 'score' — map names
                // are already added; keep order stable.
                // scale_value is optional (blank for DIRECT_POINTS/WEIGHTED_POINTS)
                // but REQUIRED per row when scoring_mode=WEIGHTED_SCALE — shipped as a
                // documented column so a WEIGHTED_SCALE import has somewhere to put it.
                if (!headers.contains("scale_value")) headers.add("scale_value");
                if (!headers.contains("factor_weight")) headers.add("factor_weight");
                if (!headers.contains("level_points")) headers.add("level_points");
                if (!headers.contains("level_order")) headers.add("level_order");
                if (!headers.contains("level_description")) headers.add("level_description");
            }
            case ImportTemplateCode.GRADE_BANDS_V1 -> {
                if (!headers.contains("description")) headers.add("description");
            }
            default -> { /* no-op */ }
        }
    }
}
