replicaCount: 2
runtimeConfig:
  apiBaseUrl: "/api"
  environment: "production"
ingress:
  enabled: true
  hosts:
    - host: grading.hrlab.uz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: grading-frontend-prod-tls
      hosts:
        - grading.hrlab.uz
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 65
pdb:
  enabled: true
  minAvailable: 1
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: grading-frontend
imagePullSecrets:
  - name: ghcr-pull-secret
